using System;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;

namespace SafeSite.Build.Headset
{
    /// <summary>
    /// Installs the per-headset AndroidManifest before a build.
    ///
    /// Assets/Plugins/Android/AndroidManifest.xml is applied to every Android build, so the single
    /// hand-written Quest manifest that used to live there shipped inside the PICO APK as well -
    /// the 0.1.1 PICO build declared com.oculus.intent.category.VR, com.oculus.supportedDevices
    /// ("quest|quest2|questpro|quest3|quest3s") and a horizonos:uses-horizonos-sdk element. That
    /// file is now generated from a per-device template and should not be edited directly; edit the
    /// templates under ManifestTemplates/ instead.
    /// </summary>
    public static class HeadsetAndroidManifest
    {
        private const string TemplateDir = "Assets/Editor/HeadsetBuild/ManifestTemplates";
        private const string OutputPath = "Assets/Plugins/Android/AndroidManifest.xml";

        private const string GeneratedBanner =
            "<!-- GENERATED by HeadsetAndroidManifest from ManifestTemplates/AndroidManifest.{0}.xml. Do not edit; edit the template. -->";

        public static void Apply(HeadsetDevice device)
        {
            var templatePath = $"{TemplateDir}/AndroidManifest.{device}.xml";
            if (!File.Exists(templatePath))
                throw new BuildFailedException($"Missing AndroidManifest template for {device} at '{templatePath}'.");

            var contents = File.ReadAllText(templatePath);

            // Keep the banner below the XML declaration - a comment before it is not well-formed.
            var declarationEnd = contents.IndexOf("?>", System.StringComparison.Ordinal);
            var banner = string.Format(GeneratedBanner, device);
            contents = declarationEnd < 0
                ? banner + "\n" + contents
                : contents.Insert(declarationEnd + 2, "\n" + banner);

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));

            // Skip the write (and the reimport it triggers) when nothing actually changes.
            if (File.Exists(OutputPath) && File.ReadAllText(OutputPath) == contents)
            {
                Debug.Log($"[HeadsetBuild] AndroidManifest already matches the {device} template.");
                return;
            }

            File.WriteAllText(OutputPath, contents);
            AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);
            Debug.Log($"[HeadsetBuild] Installed the {device} AndroidManifest at '{OutputPath}'.");
        }

        /// <summary>Fails the build if the installed manifest is not the one this target needs.</summary>
        public static void Validate(HeadsetDevice device)
        {
            if (!File.Exists(OutputPath))
                throw new BuildFailedException($"No AndroidManifest at '{OutputPath}'. Run the build via the Build menu.");

            var contents = File.ReadAllText(OutputPath);
            var expected = string.Format(GeneratedBanner, device);

            if (!contents.Contains(expected))
                throw new BuildFailedException(
                    $"'{OutputPath}' was not generated from the {device} template. It may have been hand-edited or " +
                    $"left over from the other headset - rebuild through the Build menu.");

            var foreignMarkers = device == HeadsetDevice.Pico
                ? new[] { "com.oculus.intent.category.VR", "com.oculus.supportedDevices", "horizonos" }
                : new[] { "pvr.app.type" };

            // Scan the markup only. The templates document the markers they deliberately leave out,
            // and a comment mentioning one is not the same as declaring it.
            var markup = StripXmlComments(contents);

            foreach (var marker in foreignMarkers)
            {
                if (markup.Contains(marker))
                    throw new BuildFailedException(
                        $"The {device} AndroidManifest declares the foreign-vendor marker '{marker}'.");
            }
        }

        private static string StripXmlComments(string xml)
        {
            var builder = new System.Text.StringBuilder(xml.Length);
            var index = 0;

            while (index < xml.Length)
            {
                var open = xml.IndexOf("<!--", index, StringComparison.Ordinal);
                if (open < 0)
                {
                    builder.Append(xml, index, xml.Length - index);
                    break;
                }

                builder.Append(xml, index, open - index);

                var close = xml.IndexOf("-->", open + 4, StringComparison.Ordinal);
                if (close < 0)
                    break; // Unterminated comment: everything after it is commented out.

                index = close + 3;
            }

            return builder.ToString();
        }
    }
}
